from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("version.json", views.version_info, name="version_info"),
    path("manifest.json", views.manifest, name="manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("offline/", views.offline_page, name="offline_page"),
    path("pwa/pasang/", views.pwa_install, name="pwa_install"),
    path("login/", auth_views.LoginView.as_view(template_name="attendance/login.html"), name="login"),
    path("login-wajah/", views.face_login, name="face_login"),
    path("lupa-kata-laluan/", views.password_recovery_request, name="password_recovery_request"),
    path("lupa-kata-laluan/status/", views.password_recovery_status, name="password_recovery_status"),
    path("pulih-kata-laluan/", views.password_recovery_confirm, name="password_recovery_confirm"),
    path("pulih-kata-laluan/qr/<int:pk>/<str:code>/", views.password_recovery_qr_scan, name="password_recovery_qr_scan"),
    path("pulih-kata-laluan/qr/tukar/", views.password_recovery_qr_set, name="password_recovery_qr_set"),
    path("pemulihan-kata-laluan/admin/", views.password_recovery_admin, name="password_recovery_admin"),
    path("pemulihan-kata-laluan/<int:pk>/lulus/", views.password_recovery_approve, name="password_recovery_approve"),
    path("pemulihan-kata-laluan/<int:pk>/tolak/", views.password_recovery_reject, name="password_recovery_reject"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("profil/", views.profile_page, name="profile_page"),
    path("dashboard-admin/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard-admin/live/", views.dashboard_live_data, name="dashboard_live_data"),
    path("peta-kehadiran/", views.attendance_map, name="attendance_map"),
    path("rekod/<str:action>/", views.record_attendance, name="record_attendance"),
    path("cuti/", views.leave_page, name="leave_page"),
    path("cuti/<int:pk>/batal/", views.leave_cancel, name="leave_cancel"),
    path("pengurusan-cuti/", views.leave_admin, name="leave_admin"),
    path("pengurusan-cuti/<int:pk>/<str:decision>/", views.leave_review, name="leave_review"),
    path("tugas-rasmi/", views.duty_page, name="duty_page"),
    path("laporan/", views.report_page, name="report_page"),
    path("laporan/excel/", views.export_excel, name="export_excel"),
    path("laporan/pdf/", views.export_pdf, name="export_pdf"),
    path("import-guru/", views.import_teachers, name="import_teachers"),
    path("log-audit/", views.audit_log_page, name="audit_log_page"),
    path("log-audit/export-csv/", views.audit_log_export_csv, name="audit_log_export_csv"),
    path("log-audit/reset-semua/", views.audit_log_reset_all, name="audit_log_reset_all"),
    path("keselamatan-peranti/", views.device_security_page, name="device_security_page"),
    path("keselamatan-peranti/<int:pk>/<str:status>/", views.device_update_status, name="device_update_status"),
    path("notifikasi/", views.notification_center, name="notification_center"),
    path("notifikasi/<int:pk>/baca/", views.notification_mark_read, name="notification_mark_read"),
    path("notifikasi/baca-semua/", views.notification_mark_all_read, name="notification_mark_all_read"),
    path("push/public-key/", views.push_public_key, name="push_public_key"),
    path("push/subscribe/", views.push_subscribe, name="push_subscribe"),
    path("push/unsubscribe/", views.push_unsubscribe, name="push_unsubscribe"),
]
