"""Maklumat keluaran rasmi aplikasi."""
APP_VERSION = "10.7"
APP_VERSION_LABEL = "V10.7"
APP_RELEASE_CHANNEL = "stable"
APP_RELEASE_DATE = "2026-07-30"
APP_RELEASE_NAME = "eHadir Guru Enterprise V10.7 – School Management Center"
APP_BUILD_NUMBER = "10.7.001"
APP_DEVELOPER = "eHadir Guru Enterprise Team"
