"""Maklumat keluaran rasmi aplikasi."""
APP_VERSION = "10.5.1"
APP_VERSION_LABEL = "V10.5.1"
APP_RELEASE_CHANNEL = "stable"
APP_RELEASE_DATE = "2026-07-30"
APP_RELEASE_NAME = "Sistem Kehadiran Guru V10.5.1 – Role Working Schedule & Management Attendance"
