"""Maklumat keluaran rasmi aplikasi."""
APP_VERSION = "11.0"
APP_VERSION_LABEL = "V11.0"
APP_RELEASE_CHANNEL = "enterprise"
APP_RELEASE_DATE = "2026-07-30"
APP_RELEASE_NAME = "eHadir Guru Enterprise V11.0 – Enterprise Foundation"
APP_BUILD_NUMBER = "11.0.001"
APP_DEVELOPER = "Raimol Salati"
APP_COMPANY = "Emoz San Technologies"
APP_PRODUCT = "eHadir Guru Enterprise"
APP_COPYRIGHT = "© 2026 Emoz San Technologies. All Rights Reserved."
